apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: search-service
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: {{ .Values.global.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: search-service
