// Jenkinsfile — notification-service
// Calls the shared springBootPipeline step.
// All pipeline logic lives in the shared library.

@Library('sssm-shared-library') _

springBootPipeline(
    serviceName: 'notification-service',
    servicePort:  8085
)
