apiVersion: v1
kind: Service
metadata:
  name: user-analysis-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: user-analysis-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: user-analysis-service
