image:
  repository: "{{ .Values.global.registry }}/search-service"
  tag: "1.0.0"

replicaCount: 2

service:
  type: ClusterIP
  port: 8086

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }
    - type: Resource
      resource:
        name: memory
        target: { type: Utilization, averageUtilization: 80 }

resources:
  requests:
    cpu:    500m
    memory: 1Gi
  limits:
    cpu:    "2"
    memory: 2Gi

env:
  SPRING_PROFILES_ACTIVE: prod
  SERVER_PORT: "8086"
  TRACING_SAMPLE_RATE: "0.1"

externalSecrets:
  - secretName: search-service-secrets
    remoteRef:  sssm/prod/search-service
    keys:
      - OPENSEARCH_HOST
      - OPENSEARCH_PORT
      - KAFKA_BOOTSTRAP_SERVERS
      - KAFKA_SASL_USERNAME
      - KAFKA_SASL_PASSWORD

dbInit:
  enabled: false


livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8086
  initialDelaySeconds: 60
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8086
  initialDelaySeconds: 30
  periodSeconds: 10

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app: search-service
