apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: media-guard-service
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: {{ .Values.global.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: media-guard-service
